### ISSUE TITLE
Cilium install

### ISSUE THREAD

**Issue by brunnels** [fenio/homelab#6]
In the flux-cluster-template there's a helm chart for cilium that is installed with ansible.  How did you install cilium for k0s?

I was also wondering if it's possible to switch to only cilium and remove metallb like was recently done in the flux-cluster-template.  Would this work in k0s?

I'm also working on a HA setup using [node-local load balancing](https://docs.k0sproject.io/v1.28.4+k0s.0/nllb/) rather than kube-vip like I would have in k3s.  I have 3 controllers and keepalived running on each controller to give a single controller k8s API IP like kube-vip would have provided.  Have you tried the same?

**Comment by fenio** [comment]
I guess you noticed that I'm using Cilium based on some artifacts I've got in repo ;)

I'm going to update README.md at some point to show the way I'm installing it but just especially for you I'm pasting my new k0sctl config:

```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: lab
spec:
  hosts:
  - ssh:
      address: 10.10.20.99
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: controller
    installFlags:
    - --disable-components=metrics-server
  - ssh:
      address: 10.10.20.101
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
  - ssh:
      address: 10.10.20.102
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
  - ssh:
      address: 10.10.20.103
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
  k0s:
    version: 1.28.4+k0s.0
    dynamicConfig: false
    config:
      spec:
        network:
          provider: custom
          kubeProxy:
            disabled: true
        extensions:
          helm:
            repositories:
            - name: cilium
              url: https://helm.cilium.io
            charts:
            - name: cilium
              chartname: cilium/cilium
              version: "1.14.4"
              namespace: kube-system
              values: |2
                bgpControlPlane:
                  enabled: true
                bgp:
                  enabled: false
                  announce:
                    loadbalancerIP: true
                    podCIDR: false
                kubeProxyReplacement: "strict"
                k8sServiceHost: 10.10.20.99
                k8sServicePort: 6443
                global:
                  encryption:
                    enabled: true
                    nodeEncryption: true
                operator:
                  replicas: 1
                ipam:
                  mode: "kubernetes"
                  operator:
                    clusterPoolIPv4PodCIDR: "10.20.0.0/16"
                    clusterPoolIPv4MaskSize: 24
```

I also tried to deploy Cilium configuration using install manifest deployer but that approach failed as it simply tries to install them before CRDs are in placed so I moved extra objects to repository
https://github.com/k0sproject/k0sctl/issues/286#issuecomment-1873539791

Hope that helps. I didn't consider using HA so I have no comments wrt to that.
